### ISSUE TITLE
Lock dates from being in the future

### ISSUE THREAD

**Issue by iDVB** [iDVB/chrome-gscheduler#18]
Lock dates from being in the future

Simply lock the user out from saving a date that is in the future.
I assume the ux would be that if the user manually edits it into the future... the field swaps it back to what it was before. Or when they use the date picker, maybe those options are greyed out?

**Comment by JAhaber** [comment]
Date field has been updated to no longer allow future date entries.

https://github.com/iDVB/chrome-gscheduler/pull/50
