### ISSUE TITLE
Create extension Options Page

### ISSUE THREAD

**Issue by iDVB** [iDVB/chrome-gscheduler#20]
Right-Click Chrome Extension Icon/Button exposes option to open Options Page
- Add to OptionsPage: **Sequence** or **Actual** time entrys
- Add to OptionsPage: **HotKey** change
- Add to OptionsPage: **Auto-reminder** Option
           - If the screen has not been opened in "X mins" and there is a task running, pop it up.

![Right-Click](http://goo.gl/8InVZM)

**Comment by JAhaber** [comment]
Options have been added in the latest build.

**Comment by JAhaber** [comment]
https://github.com/iDVB/chrome-gscheduler/pull/30
