### ISSUE TITLE
Pasting in a STOP time and then deleting it does not restart the counter

### ISSUE THREAD

**Issue by iDVB** [iDVB/chrome-gscheduler#23]
Pasting in a STOP time and then deleting it does not restart the counter
[Video of Issue](http://www.screencast.com/t/8NUoSCwpSnK7)

**Comment by JAhaber** [comment]
It is no longer possible to edit the stop time while a project is ticking. Once a project is stopped it cannot be restarted.

https://github.com/iDVB/chrome-gscheduler/pull/44
