### ISSUE TITLE
After pressing enter in the notes field the focus should jump back to the first field to prepare for another task entry

### ISSUE THREAD

**Issue by iDVB** [iDVB/chrome-gscheduler#26]
After pressing enter in the notes field the focus should jump back to the first field to prepare for another task entry

http://www.screencast.com/t/UDqVtBM73Rdo

**Comment by JAhaber** [comment]
This has been fixed in the latest build.

**Comment by JAhaber** [comment]
https://github.com/iDVB/chrome-gscheduler/pull/30
