### ISSUE TITLE
Saving tasks to Genome is irreversible

### ISSUE THREAD

**Issue by iDVB** [iDVB/chrome-gscheduler#31]
There needs to be a way to either back out of a save... or a way to put them back into GScheduler so you can assess what happened. Just lost my whole task list from the day before when something broke on save.

After clicking "Save" there should be a undo button so that you can pull the saved tasks (that were removed) back into you gscheduler list.

**Comment by JAhaber** [comment]
There is now an undo button that appears after you have saved tasks. You will have the option to restore all the tasks from your last save at any point until you: a) Save new tasks or b) remove the backup (there is a button for this)

https://github.com/iDVB/chrome-gscheduler/pull/50
