### ISSUE TITLE
Extension Tray Button/Icon does nothing currently

### ISSUE THREAD

**Issue by iDVB** [iDVB/chrome-gscheduler#5]
Click should open/close scheduler. 
Double-Click should open Genome Schedule.

**Comment by JAhaber** [comment]
I have added this feature on my copy of the repo.

**Comment by iDVB** [comment]
FYI, you don't need to, and likely best not to, comment about things in
your repo/branch. Unless your enters ion is to have people use your fork,
bad idea.  Just submit me a PR and ensure all your commits have the proper
msgs with ticket# fixed.

**Comment by iDVB** [comment]
Looks good. However, clicking once should open the window. Waiting more then the "double-click" amount of time and then single clicking again should _close_ the window. 

However, it open's and then closes it all in one.
