### ISSUE TITLE
New Less-Ugly UI

### ISSUE THREAD

**Issue by iDVB** [iDVB/chrome-gscheduler#6]
nuff said

**Comment by JAhaber** [comment]
I have styled all of the current elements on my fork. More styling will be needed when the additional features are added.

**Comment by iDVB** [comment]
Thanks Josh.
Please follow the steps for submitting a pull request here. (Where
appropriate)
https://github.com/angular/angular/blob/master/CONTRIBUTING.md#submit-pr

I'll look over the PL and approve.

Cheers,
D

**Comment by iDVB** [comment]
Looks great. Just a few things we might want to polish...

![styles](http://goo.gl/Q05Xlt)
