### ISSUE TITLE
When you save your schedule the day after, it's saving this day instead of the day before

### ISSUE THREAD

**Issue by fmaronnaud** [iDVB/chrome-gscheduler#7]
Hello,

I used the plugin yesterday but forgot to save. I did it this morning and instead of outputing the data for the previous day, it's doing it for the current day.

Best explanation ever

**Comment by JAhaber** [comment]
This should be fixed now on my repo.

**Comment by iDVB** [comment]
Thanks Josh. FYI, I'll close the tickets just need you to list whichever
tickets you fixed in your commit msgs and send a PR.

D
